version: '3.8'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: bboard2
      MYSQL_PASSWORD: bboard2password
      MYSQL_DATABASE: bboard2
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5

  web:
    build:
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    restart: always
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

#volumes:
#  mysql_data: