"""empty message

Revision ID: 34a54fc1e972
Revises: dc8a24903e00
Create Date: 2023-12-12 05:06:51.316856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '34a54fc1e972'
down_revision: Union[str, None] = 'dc8a24903e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('live_city', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('type_profession', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'users', 'cities', ['live_city'], ['live_city'])
    op.create_foreign_key(None, 'users', 'professions', ['type_profession'], ['type_profession'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'type_profession')
    op.drop_column('users', 'live_city')
    # ### end Alembic commands ###
