"""Init table

Revision ID: 725bf7113f93
Revises: 
Create Date: 2023-12-08 05:59:27.094658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '725bf7113f93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('car_model', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('car_model'),
    sa.UniqueConstraint('car_model')
    )
    op.create_table('cities',
    sa.Column('live_city', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('live_city'),
    sa.UniqueConstraint('live_city')
    )
    op.create_table('professions',
    sa.Column('type_profession', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('type_profession'),
    sa.UniqueConstraint('type_profession')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('professions')
    op.drop_table('cities')
    op.drop_table('cars')
    # ### end Alembic commands ###
