"""empty message

Revision ID: 973e77ce5476
Revises: 68c1856e07fb
Create Date: 2023-12-20 17:50:39.342440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '973e77ce5476'
down_revision: Union[str, None] = '68c1856e07fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    op.drop_constraint('users_ibfk_3', 'users', type_='foreignkey')
    op.drop_constraint('users_ibfk_2', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'professions', ['type_profession'], ['type_profession'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'users', 'cities', ['live_city'], ['live_city'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_ibfk_2', 'users', 'cities', ['live_city'], ['live_city'])
    op.create_foreign_key('users_ibfk_3', 'users', 'professions', ['type_profession'], ['type_profession'])
    op.create_index('email', 'users', ['email'], unique=False)
    # ### end Alembic commands ###
