"""empty message

Revision ID: aa2dd90ad41c
Revises: b9db3100f0da
Create Date: 2023-12-11 05:17:18.316129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'aa2dd90ad41c'
down_revision: Union[str, None] = 'b9db3100f0da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('car_model', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'users', 'cars', ['car_model'], ['car_model'])
    op.drop_column('users', 'user_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_data', mysql.TEXT(), nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'car_model')
    # ### end Alembic commands ###
